version: '3'
services:
  postgres:
    image: postgres:10.3
    ports:
      - "5432"
  web:
    build: .
    env_file:
      - .env
    command: bash -c "(bundle check || bundle install) && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/example
    ports:
      - "80:3000"
    depends_on:
      - postgres

  delayed_job:
    build: .
    env_file:
      - .env
    command: rake jobs:work
    volumes:
      - .:/example
    ports:
      - "1080:1080"
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    environment:
     - DEV_DATABASE_HOST=postgres
