ShoppingCartProduct.create(title: "California Maki Sesamo", description:"Roll kanikama, palta, envuelto en sésamo", sku:10001, price: 4500)
ShoppingCartProduct.create(title: "California Maki Masago", description:"Roll kanikama, palta, envuelto en masago", sku:10002, price: 4500)
ShoppingCartProduct.create(title: "California Ebi Mix", description:"Roll kanikama, palta, envuelto en mezcla de masago y sésamo", sku:10003, price: 4700)
ShoppingCartProduct.create(title: "California Ebi Sésamo", description:"Roll con camarón, palta, envuelto en sésamo", sku:10004, price: 4700)
ShoppingCartProduct.create(title: "California Sake Masago", description:"Roll con camarón, palta, envuelto en masago", sku:10005, price: 4700)
ShoppingCartProduct.create(title: "California Sake Sésamo", description:"Roll salmón, palta, envuelto en sésamo", sku:10006, price: 4900)
ShoppingCartProduct.create(title: "California Sake Masago", description:"Roll salmón, palta, envuelto en masago", sku:10007, price: 4900)
ShoppingCartProduct.create(title: "California Maguro Sésamo", description:"Roll atún, palta, envuelto en sésamo", sku:10008, price: 4900)
ShoppingCartProduct.create(title: "California Maguro Masago", description:"Roll atún, palta, envuelto en masago", sku:10009, price: 4900)
ShoppingCartProduct.create(title: "Ebi", description:"Roll con camarón y palta, envuelto en palta", sku:10010, price: 4900)
ShoppingCartProduct.create(title: "Ebi Especial", description:"Roll con camarón, queso crema, cebollín, envuelto en palta", sku:10011, price: 5700)
ShoppingCartProduct.create(title: "Turo", description:"Roll con salmón ahumado, camarón y queso crema, envuelto en palta", sku:10012, price: 5700)
ShoppingCartProduct.create(title: "Coca", description:"Roll con camarón y queso crema, envuelto en palta", sku:10013, price: 5700)
ShoppingCartProduct.create(title: "Akita", description:"Roll kanikama y queso crema, envuelto en palta", sku:10014, price: 4900)
ShoppingCartProduct.create(title: "Delicia", description:"Roll con camarón, queso crema y ciboulette, envuelto en palta", sku:10015, price: 5700)
ShoppingCartProduct.create(title: "Beto", description:"Roll con salmón, camarón y queso crema, envuelto en palta", sku:10016, price: 5700)
ShoppingCartProduct.create(title: "Avocado", description:"Roll salmón y queso crema, envuelto en palta", sku:10017, price: 5700)
ShoppingCartProduct.create(title: "Maki Salmón", description:"Kanikama, palta y queso crema envuelto en salmón", sku:10018, price: 5700)
ShoppingCartProduct.create(title: "Ebi Salmón", description:"Camarón y palta envuelto en salmón", sku:10019, price: 5700)
ShoppingCartProduct.create(title: "Ebi Salmón Especial", description:"Camarón, queso crema y cebollín, envuelto en salmón", sku:10020, price: 5900)
ShoppingCartProduct.create(title: "Maguro Salmón", description:"Atún, palta y cebollín, envuelto en salmón", sku:10021, price: 5900)
ShoppingCartProduct.create(title: "Sake Ciboulette", description:"Salmón, palta y queso crema envuelto en Ciboulette", sku:10022, price: 5500)
ShoppingCartProduct.create(title: "Maguro Ciboulette", description:"Atún, palta y queso crema envuelto en Ciboulette", sku:10023, price: 5500)
ShoppingCartProduct.create(title: "Vegan Sésamo", description:"Roll vegano con palta, cebollín y ciboulette envuelto en sésamo", sku:10024, price: 4900)
ShoppingCartProduct.create(title: "Vegan Masago", description:"Roll vegano con palta, cebollín y ciboulette envuelto en masago", sku:10025, price: 4900)
ShoppingCartProduct.create(title: "Nigiri Avocado", description:"Nigiri con salmón, palta y queso crema", sku:20001, price: 2700)
ShoppingCartProduct.create(title: "Nigiri Ebi", description:"Nigiri con camarón", sku:20002, price: 2700)
ShoppingCartProduct.create(title: "Nigiri Sake", description:"Nigiri con salmón", sku:20003, price: 2700)
ShoppingCartProduct.create(title: "Nigiri Maguro", description:"Nigiri con atún", sku:20004, price: 2700)
ShoppingCartProduct.create(title: "Nigiri Maguro Especial", description:"Nigiri con atún, palta y queso crema", sku:20005, price: 2700)
ShoppingCartProduct.create(title: "Sashimi Salmón 9 cortes", description:"Sashimi de salmón, 9 cortes", sku:30001, price: 7900)
ShoppingCartProduct.create(title: "Sashimi Salmón 12 cortes", description:"Sashimi de salmón, 12 cortes", sku:30002, price: 9900)
ShoppingCartProduct.create(title: "Sashimi Salmón 15 cortes", description:"Sashimi de salmón, 15 cortes", sku:30003, price: 12500)
ShoppingCartProduct.create(title: "Sashimi Atún 9 cortes", description:"Sashimi de atún, 9 cortes", sku:30004, price: 7900)
ShoppingCartProduct.create(title: "Sashimi Atún 12 cortes", description:"Sashimi de atún, 12 cortes", sku:30005, price: 9900)
ShoppingCartProduct.create(title: "Sashimi Atún 15 cortes", description:"Sashimi de atún, 15 cortes", sku:30006, price: 12500)
ShoppingCartProduct.create(title: "Sashimi Mix 12 cortes", description:"Mix de 6 cortes de sashimi de atún y 6 cortes de sashimi de salmón", sku:30007, price: 9900)
ShoppingCartProduct.create(title: "Sashimi Mix 18 cortes", description:"Mix de 9 cortes de sashimi de atún y 9 cortes de sashimi de salmón", sku:30008, price: 15990)

